name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and test
        run: |
          make
          ./run_tests.sh
          
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [msvc, clang-cl]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and test
        run: |
          msbuild
          .\run_tests.ps1
